### ISSUE TITLE
Compatibility with ES 1.1

### ISSUE THREAD

**Issue by tad-lispy** [monterail/elasticsearch-analysis-morfologik#4]
It doesn't seem to be working with ES 1.1.0. Does it?

I've installed it without problems, but when I

```
GET /_analyze?analyzer=morfologik
{ "Dwoje kotów" }
```

I get:

```
{
   "error": "ElasticsearchIllegalArgumentException[failed to find analyzer [morfologik]]",
   "status": 400
}
```

Am I doing something wrong? I'm very new to ES - only beginning to learn.

**Comment by tad-lispy** [comment]
Hi, @teamon 

I've found this fork: https://github.com/EE/elasticsearch-analysis-morfologik/commit/ffb9631f96c0612038a5e668a604aabad4aad4bc . They claim it's compatible with es 1.1 but I can't build it (I have no clue about Maven and Java in general). Could you please take a look at it and help me there? Thanks :)

**Comment by teamon** [comment]
/cc @chytreg :)---
Tymon Tobolski
CTO Monterail.com

**Comment by pySilver** [comment]
any news with this issue?

**Comment by dgertych-monterail** [comment]
@pySilver @lzrski I've made builds for two latests versions. If you still need 1.1 support just built from master with proper ES version

**Comment by tad-lispy** [comment]
Thanks a lot.

BTW I've tried both 2.3.1 and 2.3.0 on ES 1.1.0 and it seems to _just work_ with:
​​

``` shell
bin/plugin -install com.github.chytreg/elasticsearch-analysis-morfologik/2.3.1
```

I've tested only `/_analyze` endpoint, but it did it's magic, so I guess everything else should work as well.
